import { useApp } from '../context/AppContext';
import { Layout } from './Layout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { DollarSign, TrendingUp, TrendingDown, Receipt, Users } from 'lucide-react';

export function FinancialDashboard() {
  const { bills, patients, doctors, visits } = useApp();

  const totalRevenue = bills.reduce((sum, b) => sum + b.paidAmount, 0);
  const totalBilled = bills.reduce((sum, b) => sum + b.totalAmount, 0);
  const outstanding = totalBilled - totalRevenue;
  const paidBills = bills.filter(b => b.status === 'paid').length;
  const pendingBills = bills.filter(b => b.status === 'pending').length;

  // Doctor-wise revenue
  const doctorRevenue = doctors.map(doctor => {
    const doctorVisits = visits.filter(v => v.doctorId === doctor.id && v.status === 'completed');
    const revenue = doctorVisits.reduce((sum, visit) => {
      const bill = bills.find(b => b.visitId === visit.id);
      return sum + (bill?.paidAmount || 0);
    }, 0);
    return {
      doctor,
      visits: doctorVisits.length,
      revenue,
    };
  }).sort((a, b) => b.revenue - a.revenue);

  // Recent transactions
  const recentTransactions = bills
    .filter(b => b.paidAmount > 0)
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 10);

  const getPatientName = (patientId: string) => {
    const patient = patients.find(p => p.id === patientId);
    return patient?.name || 'Unknown';
  };

  return (
    <Layout title="Financial Dashboard">
      <div className="space-y-6">
        {/* Financial Summary */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Total Revenue</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-green-600" />
                <span className="text-2xl text-green-600">${totalRevenue.toFixed(2)}</span>
              </div>
              <p className="text-xs text-gray-500 mt-1">Collected payments</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Outstanding Amount</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <TrendingDown className="w-5 h-5 text-red-600" />
                <span className="text-2xl text-red-600">${outstanding.toFixed(2)}</span>
              </div>
              <p className="text-xs text-gray-500 mt-1">Pending collections</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Total Billed</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <Receipt className="w-5 h-5 text-blue-600" />
                <span className="text-2xl">${totalBilled.toFixed(2)}</span>
              </div>
              <p className="text-xs text-gray-500 mt-1">{bills.length} total bills</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Collection Rate</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-purple-600" />
                <span className="text-2xl text-purple-600">
                  {totalBilled > 0 ? ((totalRevenue / totalBilled) * 100).toFixed(1) : 0}%
                </span>
              </div>
              <p className="text-xs text-gray-500 mt-1">
                {paidBills} paid / {pendingBills} pending
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          {/* Doctor Revenue */}
          <Card>
            <CardHeader>
              <CardTitle>Doctor-wise Revenue</CardTitle>
              <CardDescription>Revenue generated by each doctor</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Doctor</TableHead>
                    <TableHead className="text-right">Visits</TableHead>
                    <TableHead className="text-right">Revenue</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {doctorRevenue.map((item) => (
                    <TableRow key={item.doctor.id}>
                      <TableCell>
                        <div>
                          <p>{item.doctor.name}</p>
                          <p className="text-xs text-gray-500">{item.doctor.specialization}</p>
                        </div>
                      </TableCell>
                      <TableCell className="text-right">{item.visits}</TableCell>
                      <TableCell className="text-right text-green-600">
                        ${item.revenue.toFixed(2)}
                      </TableCell>
                    </TableRow>
                  ))}
                  {doctorRevenue.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={3} className="text-center text-gray-500 py-4">
                        No revenue data yet
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          {/* Recent Transactions */}
          <Card>
            <CardHeader>
              <CardTitle>Recent Transactions</CardTitle>
              <CardDescription>Latest payment activities</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {recentTransactions.map((bill) => (
                  <div key={bill.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                        <DollarSign className="w-5 h-5 text-green-600" />
                      </div>
                      <div>
                        <p className="text-sm">{getPatientName(bill.patientId)}</p>
                        <p className="text-xs text-gray-500">
                          {new Date(bill.createdAt).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-green-600">${bill.paidAmount.toFixed(2)}</p>
                      <p className="text-xs text-gray-500">
                        {bill.status === 'paid' ? 'Paid' : 'Partial'}
                      </p>
                    </div>
                  </div>
                ))}
                {recentTransactions.length === 0 && (
                  <p className="text-sm text-gray-500 text-center py-4">No transactions yet</p>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* All Bills */}
        <Card>
          <CardHeader>
            <CardTitle>All Bills</CardTitle>
            <CardDescription>Complete billing history</CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Bill ID</TableHead>
                  <TableHead>Patient</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Items</TableHead>
                  <TableHead className="text-right">Total</TableHead>
                  <TableHead className="text-right">Paid</TableHead>
                  <TableHead className="text-right">Balance</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {bills.map((bill) => (
                  <TableRow key={bill.id}>
                    <TableCell className="font-mono text-xs">#{bill.id.slice(-6)}</TableCell>
                    <TableCell>{getPatientName(bill.patientId)}</TableCell>
                    <TableCell className="text-sm">
                      {new Date(bill.createdAt).toLocaleDateString()}
                    </TableCell>
                    <TableCell className="text-sm">
                      {bill.items.length} item(s)
                    </TableCell>
                    <TableCell className="text-right">${bill.totalAmount.toFixed(2)}</TableCell>
                    <TableCell className="text-right text-green-600">
                      ${bill.paidAmount.toFixed(2)}
                    </TableCell>
                    <TableCell className="text-right text-red-600">
                      ${(bill.totalAmount - bill.paidAmount).toFixed(2)}
                    </TableCell>
                    <TableCell>
                      <span className={`text-xs px-2 py-1 rounded-full ${
                        bill.status === 'paid' ? 'bg-green-100 text-green-700' :
                        bill.status === 'partial' ? 'bg-yellow-100 text-yellow-700' :
                        'bg-red-100 text-red-700'
                      }`}>
                        {bill.status}
                      </span>
                    </TableCell>
                  </TableRow>
                ))}
                {bills.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center text-gray-500 py-8">
                      No bills generated yet
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
